# from pinecone import Pinecone, ServerlessSpec
# import time
# from sentence_transformers import SentenceTransformer

# model = SentenceTransformer("sentence-transformers/all-MiniLM-L6-v2")
# pc = Pinecone(api_key="pcsk_7VH2Wt_M8DP8vcE3vJ9cMMTTKFrsBFUc4PimQSBYE416cHz5nPgxD6eSYVoTJ3PXLBZW5")

# index_name = "mooligai"
# time.sleep(1)

# index = pc.Index(index_name)
# time.sleep(1)

# query = "What is Kapha?"
# query_embeddings = model.encode([query], convert_to_numpy=True)

# results = index.query(
#     namespace="ayurveda",
#     vector=query_embeddings.tolist(),
#     top_k=3,
#     include_values=False,
#     include_metadata=True
# )

# print(results)

results = {'matches': [{'id': '9659',
              'metadata': {'source': '/content/drive/MyDrive/Datasets/Ayurveda '
                                     'Dataset/ayurveda_texts/www_gaiaherbs_com_blogs_herbs_cardamom.txt',
                           'source_text': 'Cardamom: Gaia Herbs®\n'
                                          '\n'
                                          '\n'
                                          '\n'
                                          '\n'
                                          '\n'
                                          '\n'
                                          '\n'
                                          '\n'
                                          '\n'
                                          '\n'
                                          '\n'
                                          '\n'
                                          '\n'
                                          '\n'
                                          '\n'
                                          '\n'
                                          '\n'
                                          '\n'
                                          '\n'
                                          '\n'
                                          '\n'
                                          '\n'
                                          '\n'
                                          '\n'
                                          '\n'
                                          '\n'
                                          '\n'
                                          '\n'
                                          '\n'
                                          '\n'
                                          '\n'
                                          '\n'
                                          '\n'
                                          '\n'
                                          '\n'
                                          '\n'
                                          '\n'
                                          '\n'
                                          '\n'
                                          '\n'
                                          '\n'
                                          '\n'
                                          '\n'
                                          '\n'
                                          '\n'
                                          '\n'
                                          '\n'
                                          '\n'
                                          '\n'
                                          '\n'
                                          '\n'
                                          '\n'
                                          '\n'
                                          '\n'
                                          '\n'
                                          '\n'
                                          '\n'
                                          '\n'
                                          '\n'
                                          '\n'
                                          '\n'
                                          '\n'
                                          '\n'
                                          '\n'
                                          '\n'
                                          '\n'
                                          '\n'
                                          '\n'
                                          '\n'
                                          '\n'
                                          '\n'
                                          '\n'
                                          '\n'
                                          '\n'
                                          '\n'
                                          '\n'
                                          '\n'
                                          '\n'
                                          '\n'
                                          '\n'
                                          '\n'
                                          '\n'
                                          '\n'
                                          '\n'
                                          '\n'
                                          '\n'
                                          '\n'
                                          '\n'
                                          '\n'
                                          '\n'
                                          '\n'
                                          '\n'
                                          '\n'
                                          '\n'
                                          '\n'
                                          '\n'
                                          '\n'
                                          '\n'
                                          '\n'
                                          '\n'
                                          '\n'
                                          '\n'
                                          '\n'
                                          '\n'
                                          '\n'
                                          '\n'
                                          '\n'
                                          '\n'
                                          '\n'
                                          '\n'
                                          '\n'
                                          '\n'
                                          '\n'
                                          '\n'
                                          '\n'
                                          '\n'
                                          '\n'
                                          '\n'
                                          '\n'
                                          '\n'
                                          '\n'
                                          '\n'
                                          '\n'
                                          '\n'
                                          ' \n'
                                          '\n'
                                          '\n'
                                          '\n'
                                          '\n'
                                          '\n'
                                          '\n'
                                          '\n'
                                          '\n'
                                          '\n'
                                          '\n'
                                          '\n'
                                          '\n'
                                          '      Skip to content\n'
                                          '    \n'
                                          '\n'
                                          '\n'
                                          '\n'
                                          '\n'
                                          '\n'
                                          '\n'
                                          '\n'
                                          '\n'
                                          '\n'
                                          '\n'
                                          '\n'
                                          '\n'
                                          '\n'
                                          '\n'
                                          '\n'
                                          '\n'
                                          '\n'
                                          'Shop\n'
                                          '\n'
                                          '\n'
                                          '\n'
                                          '\n'
                                          'New & Featured\n'
                                          '\n'
                                          '\n'
                                          'Best Sellers\n'
                                          '\n'
                                          '\n'
                                          'New Products\n'
                                          '\n'
                                          '\n'
                                          'Bundles\n'
                                          '\n'
                                          '\n'
                                          'Gisele x Gaia Herbs\n'
                                          '\n'
                                          '\n'
                                          '\n'
                                          '\n'
                                          'Shop Popular Herbs\n'
                                          '\n'
                                          '\n'
                                          'Ashwagandha\n'
                                          '\n'
                                          '\n'
                                          'Astragalus\n'
                                          '\n'
                                          '\n'
                                          'Black Elderberry\n'
                                          '\n'
                                          '\n'
                                          'Maca Root\n'
                                          '\n'
                                          '\n'
                                          'Milk Thistle\n'
                                          '\n'
                                          '\n'
                                          'Turmeric\n'
                                          '\n'
                                          '\n'
                                          '\n'
                                          '\n'
                                          '\n'
                                          '\n'
                                          'Shop By Health Interest\n'
                                          '\n'
                                          '\n'
                                          '\n'
                                          '\n'
                                          '\n'
                                          '\n'
                                          '\n'
                                          '\n'
                                          '\n'
                                          '\n'
                                          '\n'
                                          '\n'
                                          '\n'
                                          'Immune Support\n'
                                          '\n'
                                          '\n'
                                          '\n'
                                          '\n'
                                          '\n'
                                          '\n'
                                          '\n'
                                          '\n'
                                          '\n'
                                          '\n'
                                          '\n'
                                          '\n'
                                          '\n'
                                          '\n'
                                          '\n'
                                          '\n'
                                          '\n'
                                          '\n'
                                          '\n'
                                          '\n'
                                          'Stress Support\n'
                                          '\n'
                                          '\n'
                                          '\n'
                                          '\n'
                                          '\n'
                                          '\n'
                                          '\n'
                                          '\n'
                                          '\n'
                                          '\n'
                                          '\n'
                                          '\n'
                                          '\n'
                                          '\n'
                                          '\n'
                                          '\n'
                                          '\n'
                                          '\n'
                                          '\n'
                                          '\n'
                                          '\n'
                                          '\n'
                                          '\n'
                                          '\n'
                                          '\n'
                                          '\n'
                                          '\n'
                                          '\n'
                                          '\n'
                                          '\n'
                                          'Women\n'
                                          '\n'
                                          '\n'
                                          '\n'
                                          '\n'
                                          '\n'
                                          '\n'
                                          '\n'
                                          '\n'
                                          '\n'
                                          '\n'
                                          '\n'
                                          '\n'
                                          '\n'
                                          '\n'
                                          '\n'
                                          '\n'
                                          '\n'
                                          '\n'
                                          '\n'
                                          '\n'
                                          '\n'
                                          '\n'
                                          '\n'
                                          '\n'
                                          '\n'
                                          '\n'
                                          '\n'
                                          '\n'
                                          '\n'
                                          '\n'
                                          '\n'
                                          '\n'
                                          '\n'
                                          'Men\n'
                                          '\n'
                                          '\n'
                                          '\n'
                                          '\n'
                                          '\n'
                                          '\n'
                                          '\n'
                                          '\n'
                                          '\n'
                                          '\n'
                                          '\n'
                                          '\n'
                                          '\n'
                                          '\n'
                                          '\n'
                                          '\n'
                                          'Digestive\n'
                                          '\n'
                                          '\n'
                                          '\n'
                                          '\n'
                                          '\n'
                                          '\n'
                                          '\n'
                                          '\n'
                                          '\n'
                                          '\n'
                                          '\n'
                                          '\n'
                                          '\n'
                                          '\n'
                                          '\n'
                                          '\n'
                                          '\n'
                                          '\n'
                                          '\n'
                                          '\n'
                                          '\n'
                                          '\n'
                                          '\n'
                                          '\n'
                                          'Liver & Cleanse\n'
                                          '\n'
                                          '\n'
                                          '\n'
                                          '\n'
                                          '\n'
                                          '\n'
                                          '\n'
                                          '\n'
                                          '\n'
                                          '\n'
                                          '\n'
                                          '\n'
                                          'Heart Support\n'
                                          '\n'
                                          '\n'
                                          '\n'
                                          '\n'
                                          '\n'
                                          '\n'
                                          '\n'
                                          '\n'
                                          '\n'
                                          '\n'
                                          '\n'
                                          '\n'
                                          '\n'
                                          '\n'
                                          '\n'
                                          '\n'
                                          '\n'
                                          '\n'
                                          '\n'
                                          '\n'
                                          '\n'
                                          '\n'
                                          'Brain & Cognitive Support\n'
                                          '\n'
                                          '\n'
                                          '\n'
                                          '\n'
                                          '\n'
                                          '\n'
                                          '\n'
                                          '\n'
                                          '\n'
                                          '\n'
                                          '\n'
                                          'Sleep Support\n'
                                          '\n'
                                          '\n'
                                          '\n'
                                          '\n'
                                          '\n'
                                          '\n'
                                          '\n'
                                          '\n'
                                          '\n'
                                          '\n'
                                          'Stamina & Energy Support\n'
                                          '\n'
                                          '\n'
                                          '\n'
                                          '\n'
                                          '\n'
                                          '\n'
                                          '\n'
                                          '\n'
                                          '\n'
                                          '\n'
                                          '\n'
                                          '\n'
                                          '\n'
                                          'Beauty & Radiance Support\n'
                                          '\n'
                                          '\n'
                                          '\n'
                                          '\n'
                                          '\n'
                                          '\n'
                                          'Shop All Products\n'
                                          'Subscribe & Save 15%\n'
                                          '\n'
                                          '\n'
                                          '(X) Close\n'
                                          '\n'
                                          '\n'
                                          '\n'
                                          '\n'
                                          'Learn\n'
                                          '\n'
                                          '\n'
                                          '\n'
                                          '\n'
                                          'Resources\n'
                                          '\n'
                                          '\n'
                                          'Herb Reference Guide\n'
                                          '\n'
                                          '\n'
                                          'Meet Your Herbs\n'
                                          '\n'
                                          '\n'
                                          'Our Blog\n'
                                          '\n'
                                          '\n'
                                          'Herbal FAQs'},
              'score': 0.442540169,
              'values': []},
             {'id': '9664',
              'metadata': {'source': '/content/drive/MyDrive/Datasets/Ayurveda '
                                     'Dataset/ayurveda_texts/www_gaiaherbs_com_blogs_herbs_cardamom.txt',
                           'source_text': 'Suggestions\n'
                                          '\n'
                                          'Category\n'
                                          '\n'
                                          'Pages\n'
                                          '\n'
                                          '\n'
                                          '\n'
                                          'Product Suggestions\n'
                                          '\n'
                                          '\n'
                                          '\n'
                                          '\n'
                                          'VIEW ALL  SEARCH RESULTS\n'
                                          '\n'
                                          '\n'
                                          '\n'
                                          '\n'
                                          '\n'
                                          '\n'
                                          '\n'
                                          '\n'
                                          '\n'
                                          'Caraway\n'
                                          '\n'
                                          "Cat's Claw\n"
                                          '\n'
                                          '\n'
                                          '\n'
                                          '\n'
                                          'Elettaria cardamomum\n'
                                          'Cardamom\n'
                                          'This member of the Ginger family '
                                          '(Zingiberaceae) hails from India. '
                                          'Interestingly, Guatemala is the '
                                          'largest exporter of Cardamom '
                                          'seedpods today, followed by India. '
                                          'The seeds have an incredibly '
                                          'strong, aromatic, almost '
                                          'intoxicating aroma and while black '
                                          'Pepper was called the King of '
                                          'Spices, Cardamom has been called '
                                          'the Queen. The seeds have been '
                                          'traded as a commodity and are '
                                          'reputed to be the third most '
                                          'expensive spice by weight next to '
                                          'saffron and vanilla. It has found '
                                          'its way into regional cuisine in '
                                          'India, Southeast Asia, China, '
                                          'Finland, and many other countries. '
                                          'One of the most refreshing ways to '
                                          'experience Cardamom is to drink a '
                                          'fine cup of Chai spiced with '
                                          'cardamom. The seeds contain a very '
                                          'high amount of volatile oils, '
                                          'characteristic of so many of the '
                                          'aromatic plants and have been used '
                                          'medicinally as a digestive aid by '
                                          'most cultures.'},
              'score': 0.430416763,
              'values': []},
             {'id': '1923',
              'metadata': {'source': '/content/drive/MyDrive/Datasets/Ayurveda '
                                     'Dataset/ayurveda_texts/www_artofliving_org_in-en_ayurveda_ayurvedic-tips_top-10-ayurveda-herbs-you-cannot-miss.txt',
                           'source_text': '4. Cardamom – TRANQUILIZER\n'
                                          'Cardamom is a natural tranquilizer, '
                                          'bringing clarity and joy to the '
                                          'heart and mind. It neutralizes the '
                                          'acidity of coffee and caffeine – it '
                                          'also neutralizes the mucus-forming '
                                          'properties in milk. Cardamom '
                                          'removes excess kapha from stomach '
                                          'and lungs.\n'
                                          'For the best results, add some '
                                          'cardamom pods or powder to coffee '
                                          'as you are brewing it or boil '
                                          'cardamom in warm milk and drink '
                                          'before bed.'},
              'score': 0.429365575,
              'values': []}],
 'namespace': 'ayurveda',
 'usage': {'read_units': 6}}



def get_context(retrieval_data):
    import re
    context_list = []

    for match in retrieval_data.get("matches", []):
        source_text = match.get("metadata", {}).get("source_text", "")
        cleaned_text = re.sub(r'\n+', '\n', source_text)
        meaningful_sentences = [sentence.strip() for sentence in cleaned_text.split("\n") if len(sentence.strip()) > 20]

        if meaningful_sentences:
            context_list.append("\n".join(meaningful_sentences))

    return " ".join(context_list) if context_list else "No relevant Ayurvedic context found."


print(get_context(results))